title:             Conner Malloy
email:             contact@connermalloy.com
description:       Information Technology
author:            Conner Malloy
baseurl:           "/"
url:               "http://ctmalloy.github.io"
tagline:           This is Sparta

# Social Profiles
twitter_username:  connermalloy
github_username:   ctmalloy
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
